// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuNMQb5LTohWZq8xNFyfmRwqwkon26JUQ',
    appId: '1:1011929814085:web:b10906d39e61c6e704ff2c',
    messagingSenderId: '1011929814085',
    projectId: 'messenger-app-cb63f',
    authDomain: 'messenger-app-cb63f.firebaseapp.com',
    storageBucket: 'messenger-app-cb63f.appspot.com',
    measurementId: 'G-YSD8X39ZJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwUg_9gVKOgoI_ONX-p78qeV-HiUnBCUM',
    appId: '1:1011929814085:android:7ad33c68c0713a2904ff2c',
    messagingSenderId: '1011929814085',
    projectId: 'messenger-app-cb63f',
    storageBucket: 'messenger-app-cb63f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9kr68bsNGaaYaFNE22P-8MjqMBnXwS20',
    appId: '1:1011929814085:ios:e922daf7a28572a204ff2c',
    messagingSenderId: '1011929814085',
    projectId: 'messenger-app-cb63f',
    storageBucket: 'messenger-app-cb63f.appspot.com',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9kr68bsNGaaYaFNE22P-8MjqMBnXwS20',
    appId: '1:1011929814085:ios:4f765b5f277d497004ff2c',
    messagingSenderId: '1011929814085',
    projectId: 'messenger-app-cb63f',
    storageBucket: 'messenger-app-cb63f.appspot.com',
    iosBundleId: 'com.example.messengerApp.RunnerTests',
  );
}
